-- Sprint 9A: Add FORCE ROW LEVEL SECURITY to all tenant tables
-- This ensures RLS is enforced even for table owners

-- Tables with direct workspace_id policies
ALTER TABLE documents FORCE ROW LEVEL SECURITY;
ALTER TABLE document_chunks FORCE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE chat_messages FORCE ROW LEVEL SECURITY;
ALTER TABLE analytics_events FORCE ROW LEVEL SECURITY;
ALTER TABLE prompt_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE prompt_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE mcp_servers FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_members FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_subscriptions FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_usage FORCE ROW LEVEL SECURITY;
ALTER TABLE eval_queries FORCE ROW LEVEL SECURITY;
ALTER TABLE eval_results FORCE ROW LEVEL SECURITY;
ALTER TABLE retrieval_logs FORCE ROW LEVEL SECURITY;

-- Billing tables
ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE invoice_line_items FORCE ROW LEVEL SECURITY;
ALTER TABLE payments FORCE ROW LEVEL SECURITY;
ALTER TABLE subscription_events FORCE ROW LEVEL SECURITY;

-- Newly added tables
ALTER TABLE api_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE api_usage_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE widgets FORCE ROW LEVEL SECURITY;
ALTER TABLE widget_conversations FORCE ROW LEVEL SECURITY;
ALTER TABLE widget_messages FORCE ROW LEVEL SECURITY;

-- workspaces table (uses subquery policy)
ALTER TABLE workspaces FORCE ROW LEVEL SECURITY;
